### ISSUE TITLE
Traefik

### ISSUE THREAD

**Issue by lolerfox** [snoups/3xui-shop#25]
```
Сразу заявлю, я полнейший ноль в проксировании(и возможно могу нести полную чушь,
собственно "i have autism please be patient" ;D).
```
Собственно в чем суть вопроса?
Traefik это конечно круто, но что делать если уже имеется сконфигурированный Nginx PM?

Возникает явный конфликт аллокации портов между Traefik и Nginx PM.

Я как-то не очень хочу мигрировать все прокси в Traefik,
а покупать еще один отдельный сервер только под бота как то не ахти.

Я пытался прокинуть WebHook через Nginx PM, но бот явно не хотел его цеплять.
(Опять же либо я камень, либо все грутсно).

Есть ли варианты решения данного конфликта?

**Comment by snoups** [comment]
Привет, @lolerfox!

Пробуй так:
- Убрать `traefik` из `docker-compose.yml`.
- Настроить **Nginx** на `localhost:8080`.
- Пробросить порт `8080` в контейнере `bot`.

_Изменить порт бота можно в `app/config.py`:22_

**Comment by lolerfox** [comment]
О боги... да... спасибо
Собственно оставлю для последующих кто столкнется с такой же проблемой...
Измененный Docker-compose.yaml
С биндом на порт 8045.
```
services:
  redis:
    image: redis:latest
    container_name: 3xui-shop-redis
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    container_name: 3xui-shop-bot
    ports:
      - "8045:8045"
    volumes:
      - ./app/data:/app/data
      - ./plans.json:/app/data/plans.json
      - ./app/locales:/app/locales
      - ./app/logs:/app/logs
    env_file:
      - .env
    stop_signal: SIGINT
    restart: unless-stopped
    command: sh -c " 
      poetry run pybabel compile -d /app/locales -D bot && 
      poetry run alembic -c /app/db/alembic.ini upgrade head && 
      poetry run python /app/__main__.py"
    depends_on:
      - redis

volumes:
  redis_data:
  letsencrypt_data:
```

в .env добавить
```BOT_PORT=8045```

В Nginx Proxy Manager
Создаем прокси на домен бота
```
Domain Names: Домен бота
Scheme: http
Forward Port: 8045
```

И подключаем SSL сертификат, либо свой, либо само подписанный через Let's encrypt 

Проверяем, если в браузере на ```https://{Bot Domain}/webhook``` вы получаете ошибку ```405: Method Not Allowed```, а бот нормально откликается на все команды, то поздравляю
