### ISSUE TITLE
Bot not working/Бот не работает

### ISSUE THREAD

**Issue by KotBaly** [snoups/3xui-shop#51]
Никак не получается настроить бота. Как это правильно сделать? В .env задал следующие параметры

```
BOT_TOKEN="blabla"
BOT_DEV_ID=7830643***
BOT_SUPPORT_ID=7830643***
BOT_DOMAIN=mydomain.duckdns.org

XUI_USERNAME=username
XUI_PASSWORD=password

LETSENCRYPT_EMAIL=example@email.com
```
Порт поменял с 443 на 4433 в docker-compose.yml, так как на нем висит xray. Открыл в фаерволе всевозможные порты (80, 8080, 443, 4433).  Докер запускается без ошибок, однако бот не работает.  Максимум выдает это и все. Аналогичная проблема была уже в закрытом issue #29. Может стоит написать подробный гайд по установке? Что я делаю не так? Или обязательно субдомен использовать?

![Image](https://github.com/user-attachments/assets/474ca7ec-35d0-49da-9fe6-712a62c02991)

**Comment by ilyarvmc** [comment]
Бот работает) Одну ошибку у тебя увидел. Токен без кавычек сделай. 
Чтобы корректно работали подписки в панели укажи адреса полученных сертификатов. Самоподписанные сертификаты не подойдут.

**Comment by KotBaly** [comment]
Кавычки убрал, все тоже самое. В панели в разделе "Подписка" указал сертификаты от Let's Encrypt.

**Comment by ilyarvmc** [comment]
Попробуй заполнить конфиг ниже. 
Укажи везде одинаковые id бота пока. У поддержки, админа и BOT_DEV_ID
Включи подписку в панели и укажи путь и порт как в конфиге.
У меня с конфигом ниже всё завелось ) Расскажи потом в чем была причина. 

# --- Сертификаты и домен ---
LETSENCRYPT_EMAIL=                              # Email сертификата
BOT_DOMAIN=                                     # Домен бота, я указал чисто домен без порта и тд.

# --- Telegram бот ---
BOT_TOKEN=                                      # Токен Telegram-бота
BOT_ADMINS=                                     # ID администраторов через запятую (если несколько)
BOT_DEV_ID=                                     # ID разработчика
BOT_SUPPORT_ID=                                 # ID поддержки
BOT_PORT=8080                                   # Порт для запуска бота

# --- Панель 3X-UI (авторизация) ---
XUI_USERNAME=                                   # Логин для 3X-UI
XUI_PASSWORD=                                   # Пароль для 3X-UI
XUI_SUBSCRIPTION_PORT=2096                      # Порт подписки
XUI_SUBSCRIPTION_PATH=/user/                    # Путь для подписки

# --- Магазин ---
SHOP_EMAIL=                                     # Email для отправки чеков
SHOP_CURRENCY=RUB                               # Валюта магазина

# --- Пробные подписки ---
SHOP_TRIAL_ENABLED=True                         # Включить пробную подписку для новых пользователей
SHOP_TRIAL_PERIOD=3                             # Длительность пробной подписки (дни)
SHOP_REFERRED_TRIAL_ENABLED=False               # Включить пробный период для приглашённых
SHOP_REFERRED_TRIAL_PERIOD=7                    # Длительность пробной подписки для приглашённых (дни)

# --- Реферальная система ---
SHOP_REFERRER_REWARD_ENABLED=True               # Включить реферальные вознаграждения
SHOP_REFERRER_LEVEL_ONE_PERIOD=10               # Вознаграждение (дни) 1-го уровня
SHOP_REFERRER_LEVEL_TWO_PERIOD=3                # Вознаграждение (дни) 2-го уровня

# --- Ограничения и бонусы ---
SHOP_BONUS_DEVICES_COUNT=1                      # Кол-во устройств для пробных подписок и промокодов

# --- Платежные системы ---
SHOP_PAYMENT_STARS_ENABLED=True                 # Оплата через Telegram Stars
SHOP_PAYMENT_CRYPTOMUS_ENABLED=False            # Оплата через Cryptomus
SHOP_PAYMENT_HELEKET_ENABLED=False              # Оплата через Heleket
SHOP_PAYMENT_YOOKASSA_ENABLED=False             # Оплата через YooKassa
SHOP_PAYMENT_YOOMONEY_ENABLED=False             # Оплата через YooMoney

# --- Логирование ---
LOG_LEVEL=DEBUG                                 # Уровень логов (DEBUG, INFO и т.п.)
LOG_FORMAT=%(asctime)s | %(name)s | %(levelname)s | %(message)s   # Формат логов
LOG_ARCHIVE_FORMAT=zip                          # Формат архива логов (zip, gz)

**Comment by ilyarvmc** [comment]
``

**Comment by KotBaly** [comment]
Спасибо за конфиг, но все по прежнему. Как только запускается контейнер бот отдает один раз "Bot Started" и больше не реагирует. Можешь скинуть своей docker-compose.yml? Я так подозреваю там косяк с портами. Вот мой, что не так? В самой панели может еще что-то включить нужно? Телеграм бота там же не нужно включать?
```
services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    restart: always
    ports:
      - "80:80"
      - "4433:4433"
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt_data:/letsencrypt"
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:4433"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
    labels:
      - "traefik.enable=true"

  redis:
    image: redis:latest
    container_name: 3xui-shop-redis
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    container_name: 3xui-shop-bot
    volumes:
      - ./app/data:/app/data
      - ./plans.json:/app/data/plans.json
      - ./app/locales:/app/locales
      - ./app/logs:/app/logs
    env_file:
      - .env
    stop_signal: SIGINT
    restart: unless-stopped
    command: sh -c "
      poetry run pybabel compile -d /app/locales -D bot &&
      poetry run alembic -c /app/db/alembic.ini upgrade head &&
      poetry run python /app/__main__.py"
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`${BOT_DOMAIN}`)"
      - "traefik.http.routers.bot.entrypoints=websecure"
      - "traefik.http.routers.bot.tls.certresolver=letsencrypt"
      - "traefik.http.services.bot.loadbalancer.server.port=8080"

volumes:
  redis_data:
  letsencrypt_data:
```

![Image](https://github.com/user-attachments/assets/b4c84a2d-2f07-4f92-886b-ad4961fe36a7)
